import { Navbar } from "../components";
import { font } from "../assets/fonts";
import Sidebar from "../components/layout/Sidebar";
import style from "./app.module.scss";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className} ${style.body}`}>
        <Navbar />
        <div className={style.layout}>
          {/* @ts-expect-error Async Server Component */}
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
